action_id: trunk-single-player-auto-upgrade
date: 2023-07-13 12:42:23
run: trunk upgrade cli --single-player-only -n --no-progress --on-upgrade=false --allow-daemon-restart=false
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 127
  out: ""
  err: "trunk-single-player-auto-upgrade: line 1: trunk: command not found\n"
timestamp: 1689252143
full_timestamp:
  nanos: 101451000
  seconds: 1689252143
trunk_version: 1.3.2
