action_id: trunk-upgrade-available
date: 2023-07-13 13:42:23
run: trunk upgrade --notify --allow-daemon-restart=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 127
  out: ""
  err: "trunk-upgrade-available: line 1: trunk: command not found\n"
timestamp: 1689255743
full_timestamp:
  nanos: 101695000
  seconds: 1689255743
trunk_version: 1.3.2
